#! /bin/bash

#If you're getting unrecognized presets, try this
#http://askubuntu.com/questions/237698/ffmeg-x264-presets-not-working

# originaly from http://tinyurl.com/twitch-linux from taladan
# www.youtube.com/user/taladan

# gist created by brodul

INRES="1280x800"                                            # input resolution
#OUTRES="1024x640"                                           # Output resolution
OUTRES="500x300"                                           # Output resolution
FPS="10"                                                    # target FPS
QUAL="ultrafast"    
#QUAL="high"                                           # one of the many FFMPEG preset on (k)ubuntu found in /usr/share/ffmpeg
# If you have low bandwidth, put the qual preset on 'fast' (upload bandwidth)
# If you have medium bandwitch put it on normal to medium

# Write your key in a file named .twitch_key in your home directory
#STREAM_KEY="live_27627308_68wlQKSIiSUqGj1qKitbEK3nUjME5U"   # This is your streamkey generated by jtv/twitch found at: http://www.justin.tv/broadcast/adv_other
STREAM_KEY="live_59457023_SJdUuULEl2EsXUNNXQKjt1lw1V6VWD"

avconv \
    -f x11grab -s $INRES  -r "$FPS" -i :0.0 \
    -f alsa -ac 2 -i pulse  \
    -vcodec libx264 -s $OUTRES -preset $QUAL \
    -acodec libmp3lame -ar 44100 -threads 6 -qscale 3 -b 712000  -bufsize 512k \
    -f flv "rtmp://live-lhr.justin.tv/app/$STREAM_KEY"
